### ISSUE TITLE
Unable to datafy a client instance

### ISSUE THREAD

**Issue by p-himik** [cognitect-labs/aws-api#184]
``` clojure
{:deps {com.cognitect.aws/api       {:mvn/version "0.8.505"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.11.1001"}
        com.cognitect.aws/s3        {:mvn/version "811.2.889.0"}}}
```

## Description with failing test case
```clojure
(def c (cognitect.aws.client.api/client ...))
(clojure.datafy/datafy c)
Execution error (ArityException) at cognitect.aws.client.api/client$fn (api.clj:95).
Wrong number of args (1) passed to: cognitect.aws.endpoint/fetch
```

The root cause is that `cognitect.aws.client.api/client` uses `(-> i :endpoint-provider endpoint/fetch)` but `endpoint/fetch` is an arity-2 function.

## Stack traces
```
clojure.lang.ArityException: Wrong number of args (1) passed to: cognitect.aws.endpoint/fetch
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at cognitect.aws.client.api$client$fn__40744.invoke(api.clj:95)
	at clojure.core.protocols$fn__8211$G__8206__8216.invoke(protocols.clj:182)
	at clojure.datafy$datafy.invokeStatic(datafy.clj:23)
	at clojure.datafy$datafy.invoke(datafy.clj:15)
	at dev$eval80298.invokeStatic(form-init4444870026998344791.clj:1)
	at dev$eval80298.invoke(form-init4444870026998344791.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7136)
	at clojure.core$eval.invokeStatic(core.clj:3202)
	at clojure.core$eval.invoke(core.clj:3198)
	at nrepl.middleware.interruptible_eval$evaluate$fn__5029.invoke(interruptible_eval.clj:91)
	at clojure.main$repl$read_eval_print__9112$fn__9115.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9112.invoke(main.clj:437)
	at clojure.main$repl$fn__9121.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__5055$fn__5059.invoke(interruptible_eval.clj:155)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__5157$fn__5161.invoke(session.clj:190)
	at nrepl.middleware.session$session_exec$main_loop__5157.invoke(session.clj:189)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by dchelimsky** [comment]
Fixed in https://github.com/cognitect-labs/aws-api/commit/0b32ff7563fb45342ee2f38dc8f97319b213dbd5, released today in version 0.8.568.
