### ISSUE TITLE
s3 does not support `:GeneratePresignedUrl` operation

### ISSUE THREAD

**Issue by visma-mortenschioler** [cognitect-labs/aws-api#192]
## Dependencies
``` clojure
{:deps {com.cognitect.aws/api       {:mvn/version "0.8.515"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.12.51"}
        com.cognitect.aws/s3        {:mvn/version "813.2.972.0"}}}
```

## Description with failing test case
I want to call the operation https://docs.aws.amazon.com/cli/latest/reference/s3/presign.html, which is also available in the S3 Java SDK: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html

```clojure
(require '[cognitect.aws.client.api :as aws])
(-> (aws/client {:api :s3})
    (aws/invoke {:op :GeneratePresignedUrl
                 :request {:key "foo" :bucket "bar"}}))
```
Which fails (see Stacktrace section). These are the only operations supported by the S3 client:
```clojure
(require '[cognitect.aws.client.api :as aws])
=> nil
(-> (aws/client {:api :s3})
    aws/ops
    keys
    sort)
=>
(:AbortMultipartUpload
 :CompleteMultipartUpload
 :CopyObject
 :CreateBucket
 :CreateMultipartUpload
 :DeleteBucket
 :DeleteBucketAnalyticsConfiguration
 :DeleteBucketCors
 :DeleteBucketEncryption
 :DeleteBucketIntelligentTieringConfiguration
 :DeleteBucketInventoryConfiguration
 :DeleteBucketLifecycle
 :DeleteBucketMetricsConfiguration
 :DeleteBucketOwnershipControls
 :DeleteBucketPolicy
 :DeleteBucketReplication
 :DeleteBucketTagging
 :DeleteBucketWebsite
 :DeleteObject
 :DeleteObjectTagging
 :DeleteObjects
 :DeletePublicAccessBlock
 :GetBucketAccelerateConfiguration
 :GetBucketAcl
 :GetBucketAnalyticsConfiguration
 :GetBucketCors
 :GetBucketEncryption
 :GetBucketIntelligentTieringConfiguration
 :GetBucketInventoryConfiguration
 :GetBucketLifecycle
 :GetBucketLifecycleConfiguration
 :GetBucketLocation
 :GetBucketLogging
 :GetBucketMetricsConfiguration
 :GetBucketNotification
 :GetBucketNotificationConfiguration
 :GetBucketOwnershipControls
 :GetBucketPolicy
 :GetBucketPolicyStatus
 :GetBucketReplication
 :GetBucketRequestPayment
 :GetBucketTagging
 :GetBucketVersioning
 :GetBucketWebsite
 :GetObject
 :GetObjectAcl
 :GetObjectLegalHold
 :GetObjectLockConfiguration
 :GetObjectRetention
 :GetObjectTagging
 :GetObjectTorrent
 :GetPublicAccessBlock
 :HeadBucket
 :HeadObject
 :ListBucketAnalyticsConfigurations
 :ListBucketIntelligentTieringConfigurations
 :ListBucketInventoryConfigurations
 :ListBucketMetricsConfigurations
 :ListBuckets
 :ListMultipartUploads
 :ListObjectVersions
 :ListObjects
 :ListObjectsV2
 :ListParts
 :PutBucketAccelerateConfiguration
 :PutBucketAcl
 :PutBucketAnalyticsConfiguration
 :PutBucketCors
 :PutBucketEncryption
 :PutBucketIntelligentTieringConfiguration
 :PutBucketInventoryConfiguration
 :PutBucketLifecycle
 :PutBucketLifecycleConfiguration
 :PutBucketLogging
 :PutBucketMetricsConfiguration
 :PutBucketNotification
 :PutBucketNotificationConfiguration
 :PutBucketOwnershipControls
 :PutBucketPolicy
 :PutBucketReplication
 :PutBucketRequestPayment
 :PutBucketTagging
 :PutBucketVersioning
 :PutBucketWebsite
 :PutObject
 :PutObjectAcl
 :PutObjectLegalHold
 :PutObjectLockConfiguration
 :PutObjectRetention
 :PutObjectTagging
 :PutPublicAccessBlock
 :RestoreObject
 :SelectObjectContent
 :UploadPart
 :UploadPartCopy
 :WriteGetObjectResponse)
```

## Stacktrace
(from running unsupported operation)
```
clojure.lang.ExceptionInfo: Operation not supported {:service :s3, :operation :GeneratePresignedUrl}
	at cognitect.aws.client.api.async$invoke.invokeStatic(async.clj:66)
	at cognitect.aws.client.api.async$invoke.invoke(async.clj:51)
	at cognitect.aws.client.api$invoke.invokeStatic(api.clj:130)
	at cognitect.aws.client.api$invoke.invoke(api.clj:113)
	at message_generator.s3$eval2215.invokeStatic(form-init5740616403102965197.clj:2)
	at message_generator.s3$eval2215.invoke(form-init5740616403102965197.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7136)
	at clojure.core$eval.invokeStatic(core.clj:3202)
	at clojure.core$eval.invoke(core.clj:3198)
	at clojure.main$repl$read_eval_print__9110$fn__9113.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9110.invoke(main.clj:437)
	at clojure.main$repl$fn__9119.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:79)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__923$fn__927.invoke(interruptible_eval.clj:142)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__1025$fn__1029.invoke(session.clj:171)
	at nrepl.middleware.session$session_exec$main_loop__1025.invoke(session.clj:170)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
	```

**Comment by visma-mortenschioler** [comment]
I realize now that the Cognitect API effectively mirrors the AWS Rest API only, and since generating presigned URL uses the SDK Client but not the HTTP interface, it is not included.
